services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  FRZB\Component\PhpDocReader\:
    resource: '../../{Reader,Resolver}/**'
    exclude: '../../{Helper,Exception,Tests}/**'
